import type { Question } from '../types'

export const demoQuestions: Question[] = [
  {
    id: 'demo-tgo-1',
    subject: 'tgo',
    topic: 'Логика и рассуждения',
    question: 'Какой вариант лучше всего описывает дедуктивное рассуждение?',
    options: {
      A: 'Переход от общего правила к частному выводу',
      B: 'Случайный выбор ответа',
      C: 'Переход от одного примера ко всем случаям',
      D: 'Запоминание определения без вывода',
    },
    correctAnswers: ['A'],
    explanation: 'Дедукция применяет общее правило к конкретной ситуации.',
  },
  {
    id: 'demo-tgo-2',
    subject: 'tgo',
    topic: 'Логика и рассуждения',
    question: 'Что означает термин "аргумент" в логике?',
    options: {
      A: 'Набор утверждений, где одно обосновывается другими',
      B: 'Любой спор между людьми',
      C: 'Только математическое число',
      D: 'Список случайных фактов',
    },
    correctAnswers: ['A'],
    explanation: 'Аргумент состоит из посылок и вывода.',
  },
  {
    id: 'demo-tgo-3',
    subject: 'tgo',
    topic: 'Логика и рассуждения',
    question: 'Если все A являются B, а X является A, что следует?',
    options: {
      A: 'X является B',
      B: 'X не является B',
      C: 'Все B являются A',
      D: 'Ничего нельзя сказать об X',
    },
    correctAnswers: ['A'],
    explanation: 'Это классический силлогизм: принадлежность к A влечет принадлежность к B.',
  },
  {
    id: 'demo-english-1',
    subject: 'english',
    topic: 'Грамматика',
    question: 'Choose the correct sentence.',
    options: {
      A: 'She goes to school every day.',
      B: 'She go to school every day.',
      C: 'She going to school every day.',
      D: 'She gone to school every day.',
    },
    correctAnswers: ['A'],
    explanation: 'In Present Simple, third-person singular verbs usually take -s.',
  },
  {
    id: 'demo-english-2',
    subject: 'english',
    topic: 'Лексика',
    question: 'Which word is a synonym for "rapid"?',
    options: {
      A: 'Slow',
      B: 'Fast',
      C: 'Late',
      D: 'Weak',
    },
    correctAnswers: ['B'],
    explanation: '"Rapid" means fast or quick.',
  },
  {
    id: 'demo-english-3',
    subject: 'english',
    topic: 'Грамматика',
    question: 'Complete the sentence: I have lived here ___ 2020.',
    options: {
      A: 'for',
      B: 'since',
      C: 'during',
      D: 'from',
    },
    correctAnswers: ['B'],
    explanation: 'Use "since" with a starting point in time.',
  },
  {
    id: 'demo-db-1',
    subject: 'databases',
    topic: 'Ключи и связи',
    question: 'Что такое первичный ключ?',
    options: {
      A: 'Поле, которое уникально идентифицирует запись',
      B: 'Поле для хранения только чисел',
      C: 'Любой внешний атрибут',
      D: 'Команда SQL',
    },
    correctAnswers: ['A'],
    explanation: 'Первичный ключ уникально идентифицирует каждую запись в таблице.',
  },
  {
    id: 'demo-db-2',
    subject: 'databases',
    topic: 'SQL',
    question: 'Какая SQL-команда используется для выборки данных?',
    options: {
      A: 'INSERT',
      B: 'SELECT',
      C: 'UPDATE',
      D: 'DROP',
    },
    correctAnswers: ['B'],
    explanation: 'SELECT возвращает данные из таблиц или представлений.',
  },
  {
    id: 'demo-db-3',
    subject: 'databases',
    topic: 'Ключи и связи',
    question: 'Что описывает внешний ключ?',
    options: {
      A: 'Связь с записью в другой таблице',
      B: 'Пароль администратора',
      C: 'Тип индекса для текста',
      D: 'Название базы данных',
    },
    correctAnswers: ['A'],
    explanation: 'Внешний ключ ссылается на ключ другой таблицы и поддерживает связи.',
  },
  {
    id: 'demo-algo-1',
    subject: 'algorithms',
    topic: 'Сложность алгоритмов',
    question: 'Какая сложность у бинарного поиска в отсортированном массиве?',
    options: {
      A: 'O(1)',
      B: 'O(log n)',
      C: 'O(n)',
      D: 'O(n log n)',
    },
    correctAnswers: ['B'],
    explanation: 'Бинарный поиск каждый шаг делит область поиска примерно пополам.',
  },
  {
    id: 'demo-algo-2',
    subject: 'algorithms',
    topic: 'Структуры данных',
    question: 'Какая структура данных работает по принципу LIFO?',
    options: {
      A: 'Очередь',
      B: 'Стек',
      C: 'Граф',
      D: 'Хеш-таблица',
    },
    correctAnswers: ['B'],
    explanation: 'Стек возвращает последним добавленный элемент первым.',
  },
  {
    id: 'demo-algo-3',
    subject: 'algorithms',
    topic: 'Структуры данных',
    question: 'Что обычно хранит вершины и ребра?',
    options: {
      A: 'Массив',
      B: 'Граф',
      C: 'Строка',
      D: 'Стек',
    },
    correctAnswers: ['B'],
    explanation: 'Граф состоит из вершин и ребер между ними.',
  },
]
